# Generated by Django 4.0.5 on 2022-07-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table='_notes',
        ),
    ]
