# Generated by Django 4.0.5 on 2022-07-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBeforeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('modelpk', models.BigIntegerField()),
                ('databeforeupdate', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=50)),
                ('modelpk', models.BigIntegerField()),
                ('action', models.CharField(choices=[('C', 'Create'), ('U', 'Update'), ('D', 'Delete'), ('P', 'Print'), ('S', 'Status')], default='C', max_length=1)),
            ],
        ),
    ]
