# Generated by Django 4.0.5 on 2022-07-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='databeforeupdate',
            table='_databeforeupdate',
        ),
        migrations.AlterModelTable(
            name='log',
            table='_log',
        ),
    ]
