# Generated by Django 4.0.5 on 2022-07-26 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_accounttype', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Enter Account', max_length=50, unique=True, verbose_name='Account')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Balance')),
                ('accounttype', models.ForeignKey(help_text='Select Account Type', on_delete=django.db.models.deletion.PROTECT, to='_accounttype.accounttype', verbose_name='Account Type')),
                ('parent', models.ForeignKey(blank=True, help_text='Select Parent Account', null=True, on_delete=django.db.models.deletion.PROTECT, to='_account.account', verbose_name='Sub Account of')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '_account',
                'ordering': ('name',),
            },
        ),
    ]
