# Generated by Django 4.0.5 on 2022-07-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='business',
            table='_business',
        ),
    ]
