# Generated by Django 4.0.5 on 2022-06-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Person Name', max_length=50, unique=True, verbose_name='Person Name')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
